version: '3.4'

services:
  recovery_backend:
    image: ${DOCKER_REGISTRY-}recoverybackend
    build:
      context: .
      dockerfile: Recovery_BackEnd/Dockerfile
    ports:
      - "5000:80" 

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
       - '3306:3306'
    environment:
       MYSQL_DATABASE: recovery
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  pma:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '80:80'
      environment:
        PMA_HOST: db 
     
  recovery_frontend_user:
    image: ${DOCKER_REGISTRY-}recoveryfrontenduser
    build:
      context: .
      dockerfile: Recovery_FrontEnd_User/Dockerfile
    ports:
      - "3000:80" 

volumes:
  dbdata: 


