# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - DosSantosRecovery

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0454cf6b5bfe4ea6bf85160ef54a6302 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a9212ad1f16246b785cac77921243ed7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0454cf6b5bfe4ea6bf85160ef54a6302 }}/recoverybackend:${{ github.sha }}
        file: ../Recovery_BackEnd/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DosSantosRecovery'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_910519ff5c8742b7a8dc20067a6c7c16 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0454cf6b5bfe4ea6bf85160ef54a6302 }}/recoverybackend:${{ github.sha }}'
